---
- hosts: localhost
  gather_facts: false

  vars:
    sites:
      - ip: 192.168.0.1
        token: 1-MvszzYoBpeTCkFKQSHRlirrypcjdtCVcl058fZRE57YdPhRPorytCruzgIxzkWAw
        validate_certs: false
      - ip: 192.168.0.2
        token: 1-uskZv5aFL2siXW9dlVpAINQWeqZNo1xpqDIXXm4yvtM2V8CsjxK9hINydxmye9vH
        validate_certs: false

  tasks:
    - name: update-truenas-api
      include_tasks: task.yml
      loop: '{{ sites }}'